"""
Deploy (or re-use) the CaptreApp smart contract on Algorand.

Usage:
    uv run python -m captre.contract.deploy

Reads from .env:
    ALGOD_URL           — e.g. https://testnet-api.algonode.cloud
    ALGOD_TOKEN         — leave blank for public nodes
    DEPLOYER_MNEMONIC   — 25-word mnemonic for the service/deployer account
    APP_ID              — if set, skips deployment and reuses this app id

Writes to .env (or prints) after first deploy:
    APP_ID              — the deployed application id
"""

import json
import os

from algokit_utils import AlgorandClient, OnSchemaBreak, OnUpdate, SigningAccount
from algosdk.mnemonic import to_private_key
from algosdk.v2client.algod import AlgodClient
from algosdk.v2client.indexer import IndexerClient
from dotenv import load_dotenv, set_key

load_dotenv()

ALGOD_URL = os.environ["ALGOD_URL"]
ALGOD_TOKEN = os.environ.get("ALGOD_TOKEN", "")
DEPLOYER_MNEMONIC = os.environ["DEPLOYER_MNEMONIC"]
ENV_FILE = ".env"


INDEXER_URL = os.environ.get("INDEXER_URL", "https://testnet-idx.algonode.cloud")


def get_client() -> AlgorandClient:
    return AlgorandClient.from_clients(
        AlgodClient(ALGOD_TOKEN, ALGOD_URL),
        IndexerClient("", INDEXER_URL),
    )


def deploy() -> int:
    """Deploy CaptreApp and return the app_id. Idempotent — checks APP_ID in env first."""
    existing = os.environ.get("APP_ID")
    if existing:
        print(f"[deploy] Reusing existing APP_ID={existing}")
        return int(existing)

    client = get_client()
    private_key = to_private_key(DEPLOYER_MNEMONIC)
    deployer = SigningAccount(private_key=private_key)

    # Load the compiled ARC4 app spec (generated by: algokit compile python captre_app.py)
    spec_path = os.path.join(os.path.dirname(__file__), "artifacts", "CaptreApp.arc56.json")
    if not os.path.exists(spec_path):
        raise FileNotFoundError(
            f"Compiled contract not found at {spec_path}.\n"
            "Run: algokit compile python contract/captre_app.py "
            "--out-dir src/captre/contract/artifacts --output-arc32"
        )

    with open(spec_path) as f:
        app_spec = json.load(f)

    app_factory = client.client.get_app_factory(
        app_spec=app_spec,
        default_sender=deployer.address,
        default_signer=deployer.signer,
    )

    result, _ = app_factory.deploy(
        on_schema_break=OnSchemaBreak.ReplaceApp,
        on_update=OnUpdate.UpdateApp,
    )
    app_id = result.app_id
    print(f"[deploy] CaptreApp deployed. APP_ID={app_id}  APP_ADDRESS={result.app_address}")

    # Persist to .env so the server can read it without redeploying
    set_key(ENV_FILE, "APP_ID", str(app_id))
    set_key(ENV_FILE, "APP_ADDRESS", result.app_address)

    return app_id


if __name__ == "__main__":
    deploy()
